---
title: "Appointment Analysis Dashboard"
execute:
    enabled: true
format:
    html:
        code-fold: true
theme: cosmo
---
## Analysis of Appointment Type

To understand patient visit patterns, I examined the distribution of appointment types within the dataset. The resulting table and bar plot clearly demonstrate that the majority of patients sought treatment in Chiropractic, Medical Doctor, Occupational Therapy, or Physical Therapy appointments.

```{python}
#| include: true
import seaborn as sns
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
df=pd.read_excel('/Users/shrutielangovan/Desktop/Alliance Health Project/Task 1/Dashboard Prc.xlsx')
df.head(10)
df.columns
df_long = pd.melt(df, 
                  id_vars=['Patient Number','Latitude','Longitude'], 
                  value_vars=['MD Appts', 'PT Appts', 'OT Appts','CHIRO Appts', 'ALTER-G Appts', 'CRYOTHERAPY Appts','ESTABLISHED 1 YEAR CMO F/U Appts', 'GAMEREADY Appts','NORMATECH Appts', 'SOFTWAVE Appts'], 
                  var_name='Appointment Type', value_name='Number of Appointments')
df_long = df_long.dropna()
len(df_long)

appoinment_count= df_long.groupby("Appointment Type")['Number of Appointments'].sum()
appoinment_count_df = appoinment_count.reset_index()
appoinment_count_df.columns = ['Appointment Type', 'Number of Appointments']
print(appoinment_count_df) 

fig_weekly = px.bar(appoinment_count_df[appoinment_count_df['Appointment Type'].isin(['CHIRO Appts','MD Appts','OT Appts','PT Appts'])], 
                    x="Appointment Type",
                    y="Number of Appointments", 
                    title="Appointment Distribution")
fig_weekly.show()

```

## Analysis of Patient Appointment Types and Geographic Distribution

The map below displays patient appointment locations, with markers indicating clinic locations for the most recent visits. Use the interactive filter to view clinic locations based on specific appointment types.

```{python}
#| include: true
fig_location = px.scatter_mapbox(
    df_long,
    lon='Longitude',
    lat='Latitude',
    title='Recent Appointment Locations',
    opacity=0.6,
    color='Appointment Type',
    mapbox_style='carto-positron',
    color_continuous_scale=px.colors.sequential.Cividis
)

fig_location.update_layout(
    autosize=False, height=500, width=600
)

fig_location.show()

```

## Patient Payer Type Analysis

The horizontal bar graph below displays the frequency of patient payments by payer. This analysis reveals that New Jersey Medicare Part B J12 and Horizon BCBS of New Jersey BlueCard are the most prominent payers, suggesting a significant patient base relying on these insurance plans.

```{python}
#| include: true
payers_count= df.groupby("Payer")['Patient Number'].count()
payers_count.sort_values(ascending=False)
fig = px.bar(payers_count, 
orientation='h',
title = "Frequency of Different Payers",
color_continuous_scale="Blues") 

fig.update_layout(xaxis_title="Number of Patients",showlegend=False)

fig.show()
```

